### ISSUE TITLE
Fails if `/var/cache/apt/archives/` is missing

### ISSUE THREAD

**Issue by cassidyjames** [endlessm/eos-image-builder#63]
Running on a fresh install of Endless OS 4.0.4, `eos-image-builder` fails because `/var/cache/apt/archives/` is missing.

```
$ sudo ./eos-image-builder 
[sudo] password for cassidyjames: 
+ 15:16:11 INFO run-build: Configuring image build
+ 15:16:11 INFO run-build: Loaded configuration file /sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/config/defaults.ini
+ 15:16:11 INFO run-build: Loaded configuration file /sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/config/product/eoscustom.ini
+ 15:16:11 INFO run-build: Loaded configuration file /sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/config/branch/master.ini
+ 15:16:11 INFO run-build: Loaded configuration file /sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/config/arch/amd64.ini
+ 15:16:11 INFO run-build: Loaded configuration file /sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/config/personality/base.ini
+ 15:16:11 INFO run-build: Loaded configuration file /sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/config/branch-personality/master-base.ini
+ 15:16:11 INFO run-build: Preparing build directory
+ 15:16:11 INFO run-build: Cleaning up /var/tmp/eos-image-builder
+ 15:16:11 INFO eib: Killing processes in /var/tmp/eos-image-builder
+ 15:16:11 INFO eib: Unmounting filesystems in /var/tmp/eos-image-builder
+ 15:16:11 INFO run-build: Cleaning up /var/cache/eos-image-builder
+ 15:16:11 INFO eib: Killing processes in /var/cache/eos-image-builder
+ 15:16:11 INFO eib: Unmounting filesystems in /var/cache/eos-image-builder
+ 15:16:11 INFO run-build: Ensuring all ostree checkouts mutable in /var/cache/eos-image-builder/tmp/ostree-co
+ 15:16:11 INFO run-build: Recreating build specific temporary directories
+ 15:16:11 INFO run-build: Exporting configuration to environment
+ 15:16:11 INFO run-build: Output merged configuration file to /var/cache/eos-image-builder/tmp/config.ini
+ 15:16:11 INFO run-build: Output full merged configuration file to /var/cache/eos-image-builder/tmp/fullconfig.ini
+ 15:16:11 INFO eib: Creating temporary GPG keyring /var/cache/eos-image-builder/tmp/eib-keyring.gpg
+ 15:16:11 INFO eib: Importing GPG key /sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/data/keys/eos-pub-archive-key.asc
+ 15:16:11 INFO eib: Importing GPG key /sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/data/keys/debian-archive-keyring.asc
+ 15:16:11 INFO eib: Importing GPG key /sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/data/keys/endless-archive-key.asc
+ 15:16:11 INFO run-build: Creating buildroot in /var/tmp/eos-image-builder
I: automatically chosen mode: root
I: chroot architecture amd64 is equal to the host's architecture
I: automatically chosen format: directory
I: running --setup-hook directly: /sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/helpers/mmdebstrap-setup /var/tmp/eos-image-builder
rsync: [Receiver] mkdir "/var/cache/apt/archives" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(787) [Receiver=3.2.3]
E: command failed: /sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/helpers/mmdebstrap-setup
W: listening on child socket failed: 
Traceback (most recent call last):
  File "/sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/run-build", line 612, in <module>
    main()
  File "/sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/run-build", line 609, in main
    builder.run()
  File "/sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/run-build", line 573, in run
    with ImageBuildRoot(self.builddir, self.config):
  File "/sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/run-build", line 142, in __init__
    subprocess.check_call(buildroot_cmd, env=buildroot_env)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('mmdebstrap', '--verbose', '--architectures=amd64', '--variant=minbase', '--include=attr,awscli,ca-certificates,coreutils,cpio,curl,dbus-user-session,dosfstools,dpkg-dev,endless-ca-cert,eos-keyring,eos-tech-support,exfat-fuse,exfat-utils,fdisk,flatpak,genisoimage,gir1.2-flatpak-1.0,gir1.2-glib-2.0,gir1.2-ostree-1.0,git,gnupg,grub-common,grub2,jq,json-glib-tools,libfsapfs-utils,mount,mtools,openssh-client,ostree,p7zip-full,parted,pigz,python3,python3-apt,python3-gi,python3-requests,python3-venv,qemu-utils,rsync,squashfs-tools,udev,unzip,util-linux,wget,xorriso,xz-utils,zip', '--setup-hook=/sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/helpers/mmdebstrap-setup', '--customize-hook=/sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/helpers/mmdebstrap-cleanup', '', '/var/tmp/eos-image-builder', '/var/cache/eos-image-builder/tmp/buildroot-sources.list')' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/./eos-image-builder", line 95, in <module>
    subprocess.check_call([RUN_BUILD] + sys.argv[1:])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/sysroot/home/cassidyjames/Projects/endlessm/eos-image-builder/run-build']' returned non-zero exit status 1.
```

Creating that directory resolves the issue and it is able to run.

**Comment by dbnicholson** [comment]
Oh wow, that's totally busted.
